import { buildTopicPage, type TopicSpec } from "./topic-page.ts";

const specs: TopicSpec[] = [
  {
    id: "TD-T20", moduleId: "TD-M05", title: "把评测接入 CI", type: "跟做", duration: "50 分钟", summary: "把固定评测集、阻断规则、报告和退出码接入持续集成，让 AI 质量回归与代码测试一起决定能否合并。", why: "评测只在本地偶尔运行，就无法阻止 Prompt、模型、知识库或工具变化带来的回归。", prerequisites: ["TD-T12", "TD-T14"], outcomes: ["定义快速检查与发布级评测两层 CI", "让阻断性失败返回非零退出码", "保存版本、失败样例、waiver 和审批证据"], artifact: "AI 评测 CI Workflow 与质量门禁报告",
    problem: "退款 RAG 的 API 契约测试全部通过，但新知识库导致错误自动退款承诺。CI 必须在合并时运行小型高风险集，在发布候选阶段运行完整切片，并把危险声明、越权工具和 Judge 校准失败作为独立 blocker。", workflow: ["固定 eval dataset、candidate 与 scorer 版本", "先执行 Schema、引用和禁止行为等确定性检查", "再执行语义评分及已校准 Judge，并保留逐条结果", "按 blocker 与分片阈值返回退出码，上传报告与失败样例"], scenario: "在 pull request 中把退款规则改成错误承诺。workflow 先跑 20 条 smoke eval；即使平均分仍高，只要 high-risk-refund slice 出现禁止声明，就必须 exit 1。修复后用同一数据与版本记录复跑。", code: "python3 scripts/evaluate.py --suite smoke --report reports/pr.json\nstatus=$?\npython3 scripts/check_blockers.py reports/pr.json\nexit $status", expected: "已知良好版本 exit 0；注入错误退款承诺后 exit 1 并标出具体 case；修复后恢复 0，三份报告均作为 CI artifact 保存。", failure: "CI 假绿通常是只生成报告不传播退出码、读取了旧 candidate、只看平均分或失败后 `continue-on-error`。逐项检查运行输入、门禁表达式和 job 依赖。", sourceIds: ["S03", "S04", "S27"], evidenceBoundary: "已有离线 RAG fixture 证明退出码与故障注入链路；本页扩展到通用 CI 设计，未在所有云 CI、模型 Provider 或企业审批系统上运行。",
  },
  {
    id: "TD-T21", moduleId: "TD-M05", title: "评测集、Prompt、模型、知识库和工具版本", type: "参考", duration: "40 分钟", summary: "为每次质量结论保存完整 lineage，使任何分数都能回放到当时的数据、系统和评测配置。", why: "只保存模型名和总分无法解释差异；Prompt、检索索引、工具 Schema、采样参数或 Judge 任一变化都可能改变结果。", prerequisites: ["TD-T20"], outcomes: ["设计 AI 实验版本账本", "计算并保存输入与产物哈希", "判断两次运行是否具备可比性"], artifact: "AI 评测版本与 Lineage 账本",
    problem: "一次版本 A/B 报告显示分数提升 6%，但 A 使用旧知识库和人工 Judge，B 使用新索引与模型 Judge。若没有 lineage，这个 6% 不能归因给模型，也不能支持上线。", workflow: ["记录 code commit、model snapshot 与推理参数", "记录 prompt、dataset、knowledge index、tool schema 和 scorer 版本", "保存运行环境、随机种子、时间窗和成本口径", "对不可固定依赖使用录制回放或明确标为不可比较"], scenario: "创建 run-manifest.json，比较两个候选。脚本先对除被比较变量外的字段做 diff；若同时改变模型和知识库，报告输出 confounded 而非 winner。只有单变量或预先批准的组合实验才进入发布判断。", code: "compare: model_version\nlocked: [dataset_hash,prompt_hash,kb_snapshot,tool_schema,scorer_hash,seed]\nif_locked_field_changed: INVALID_COMPARISON", expected: "每个报告能定位完整依赖；相同 manifest 可重放；受混杂变量影响的 A/B 被拒绝，不生成误导性的胜负结论。", failure: "最危险的做法是使用浮动模型别名、覆盖旧 Prompt、知识库只记日期或工具 Schema 无版本。先补快照和哈希，无法补齐时把历史结论降级为不可重放。", sourceIds: ["S05", "S24", "S28"], evidenceBoundary: "来源支持评测、生产 ML 成熟度与岗位中的 lineage 责任；账本字段是课程设计，需按目标 Provider、数据平台和合规要求扩展。",
  },
  {
    id: "TD-T22", moduleId: "TD-M05", title: "Trace、生产失败和回归集闭环", type: "跟做", duration: "55 分钟", summary: "把脱敏生产失败从 Trace 转成有来源、有审批、有版本的回归样例，并验证修复不会复发。", why: "线上问题若只留在事故文档里，下一次模型、Prompt 或工具更新仍会重复逃逸。", prerequisites: ["TD-T21"], outcomes: ["从 Trace 重建 AI 请求的关键执行路径", "安全地脱敏并转成回归样例", "建立生产反馈到数据集、修复和发布门禁的闭环"], artifact: "Trace-to-Regression 流水线与回归样例",
    problem: "生产中 Agent 错误调用 refund_order。Trace 包含用户输入、检索文档、工具参数、重试和最终答复，但也可能含 PII。测试团队需要保留故障机制而不是复制整条生产记录。", workflow: ["按 trace_id 收集模型、检索、工具、状态和最终结果", "移除 PII、凭证和无关上下文，保留风险触发条件", "由业务与安全负责人确认期望行为和阻断级别", "将样例加入回归集，修复后在 CI 与预生产复跑"], scenario: "从一条错误退款 Trace 提取最小输入：商品已激活、用户要求自动退款、检索到正确政策但 Agent 仍调用工具。脱敏后生成 eval case，先证明当前坏版本失败，再修复权限策略并复跑。", code: "python3 scripts/trace_to_case.py --trace trace.json --redact --out cases/refund-escaped.json\npython3 scripts/evaluate.py --case cases/refund-escaped.json", expected: "生成的样例不含敏感数据，保留 source_trace_hash、owner、risk_slice 和 expected_tool_policy；坏版本失败，修复版本通过。", failure: "直接复制生产日志会泄露数据，过度脱敏又会删掉触发条件。若样例不能稳定重放，检查外部状态、知识库快照和工具副作用；不能复现时保留为调查线索，不算回归资产。", sourceIds: ["S10", "S27", "S28"], evidenceBoundary: "页面依据应用评测与岗位信号构建闭环；未使用真实生产 Trace，脱敏、保留期限和审批流程必须由目标组织的隐私与安全负责人确认。",
  },
  {
    id: "TD-T23", moduleId: "TD-M05", title: "质量、延迟和成本联合门禁", type: "参考", duration: "45 分钟", summary: "在固定工作负载上同时比较质量、TTFT/TPOT/端到端延迟、Token 与调用成本，避免单指标优化伤害业务。", why: "更快、更便宜或分数更高都可能以另一个维度恶化为代价；发布决定需要明确的不可突破底线和 Pareto 选择。", prerequisites: ["TD-T20"], outcomes: ["定义带分布的 AI 工作负载", "建立质量、延迟、成本三类硬门禁", "识别 Pareto 候选并给出业务决策"], artifact: "质量-延迟-成本 Pareto 对比报告",
    problem: "候选 B 把平均延迟降低 20%，但长输入上的正确率下降，p99 TTFT 上升且工具调用翻倍。仅看平均延迟会误判为优化成功。", workflow: ["固定输入长度、输出长度、并发、工具使用和风险切片分布", "分别计算 blocker、任务质量、p50/p95/p99 延迟和单位成功成本", "先淘汰突破安全/质量/SLO 底线的候选", "在剩余候选中展示 Pareto 前沿，由产品和容量负责人选择"], scenario: "比较两个模型路由：A 质量高但贵，B 便宜但在退款长对话上下降。按普通 FAQ 与高风险退款切片计算；若 B 低风险可接受、高风险不达标，可只在低风险路由而非全量替换。", code: "gate = safety_blockers==0 and high_risk_pass>=0.98 and p95_ttft_ms<=1200 and cost_per_success<=budget\npareto = nondominated(candidates)", expected: "报告不输出一个模糊综合分，而是列出各底线、切片分布和 Pareto 候选；决策明确写出适用流量、回退条件和负责人。", failure: "平均值掩盖尾部、Token 分布不同、缓存命中不一致和失败请求未计成本都会扭曲结果。先验证 workload 与分母，再讨论模型优劣。", sourceIds: ["S24", "S29", "S31"], evidenceBoundary: "来源支持生产成熟度和 AI 质量岗位需求；示例阈值只是教学数字，必须依据真实 SLO、流量、模型价格与风险承受度重新校准。",
  },
  {
    id: "TD-T24", moduleId: "TD-M05", title: "漂移、告警、Waiver 和回滚", type: "诊断", duration: "50 分钟", summary: "把质量异常分成数据、行为、Judge、性能和成本漂移，并设计可到期的例外与经过演练的回滚路径。", why: "AI 系统会随输入、知识、模型和依赖变化；没有基线、告警和回滚，团队只能在事故发生后临时猜测。", prerequisites: ["TD-T21", "TD-T22", "TD-T23"], outcomes: ["为关键切片建立基线和漂移信号", "区分告警、调查、waiver 与阻断", "编写并演练模型/Prompt/知识库/工具回滚 Runbook"], artifact: "AI 质量事故、Waiver 与回滚 Runbook",
    problem: "退款正确率一周内缓慢下降，同时 Judge 分数却保持稳定。可能是输入分布变化、知识库过期，也可能是 Judge 漂移。需要独立检查数据和评测器，避免把错误归给模型。", workflow: ["保存质量、输入、Judge、延迟和成本基线及版本", "按风险切片检测变化并设置持续窗口，避免单点噪声", "告警后冻结相关版本，执行诊断树和回归集", "阻断时回滚；waiver 必须有 owner、补偿控制、到期时间与自动失效"], scenario: "模拟知识库索引漏掉最新政策。高风险 slice recall 连续三批下降后触发 P1；先回滚到已知索引，再验证回答、引用、工具和性能。若业务必须临时上线，waiver 仅允许只读模式并在 24 小时后自动失效。", code: "alert: high_risk_recall < baseline-0.05 for 3 windows\naction: freeze -> diagnose -> rollback(kb_snapshot) -> replay_regression\nwaiver_expires: 24h", expected: "回滚后核心切片恢复基线，版本账本和事故报告记录原因、受影响范围、恢复证据和新增回归样例；到期 waiver 自动阻断。", failure: "把阈值放宽、静默更换 Judge、只回滚模型不回滚知识库，都会让问题继续存在。若多个组件同时变化，先恢复完整已知良好 manifest，再逐个前滚。", sourceIds: ["S07", "S23", "S24"], evidenceBoundary: "NIST、ISTQB 与生产 ML 资料支持治理和回滚原则；告警窗口与处置级别是教学方案，尚未经过目标组织事故演练或生产验证。",
  },
];

export const qualitySystemPages = specs.map(buildTopicPage);
